name: egov
description: Hackathon


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  pin_code_fields: ^7.3.0
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  intl: ^0.17.0
  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.4
  flutter_local_notifications: ^12.0.2
  geolocator: ^9.0.1
  geocoding: ^2.0.5
  dartz: ^0.10.1
  provider: ^6.0.3
  socket_io_client: ^2.0.0
  flutter_screenutil: ^5.6.0
  google_maps_flutter: ^2.2.3
  flutter_polyline_points: ^1.0.0
  image_picker: ^0.8.6
  flash: ^2.0.3+3
  flutter_riverpod: ^2.1.3
  group_radio_button: ^1.3.0
  google_maps_flutter_web: ^0.4.0+5
  google_places_for_flutter: ^1.0.1
  location: ^4.4.0
  get: ^4.6.5
  nfc_manager: ^3.2.0
  pretty_qr_code: ^2.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0




flutter:


  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
